# File: .github/workflows/workflow.yml

on: [workflow_dispatch]

name: Run Azure Login With a Service Principal Secret

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
     run:
      # We keep Terraform files in the terraform directory.
        working-directory: ./Terraform/VM

    steps:
    - name: Checkout
      uses: actions/checkout@v3    
    
    - name: Azure login
      uses: azure/login@v1
      with:
          auth-type: IDENTITY          
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az account show

        
    # Setups the Terraform with required Version        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.2
        
    # initializes a working directory  
    - name: Terraform Init
      run: terraform init  
      working-directory: ./Terraform/VM
      
    # validate the syntax  
    - name: Terraform Validate
      run: terraform validate 
      working-directory: ./Terraform/VM
      
    # preview the changes in Configuration files   
    - name: Terraform Plan
      run: terraform plan 
      working-directory: ./Terraform/VM
      
    - run: terraform apply -auto-approve 
      working-directory: ./Terraform/VM
